const MEETING_TYPES = ["BOARD", "AGM", "EGM"];
const MEETING_STATUSES = ["PLANNED", "HELD", "CANCELLED"];
const COMPANY_STATUSES = [
  "ACTIVE",
  "TRANSFERRED",
  "UNDER_INCORPORATION",
  "DORMANT",
  "CLOSED",
  "OTHER",
];

export { MEETING_TYPES, MEETING_STATUSES, COMPANY_STATUSES };
